version: 2
jobs:
  bats-unit-test:
    machine: true
    steps:
      - checkout
      - run: make test-image
      - run: make test-unit
  acceptance:
    docker:
        # This image is build from test/docker/Test.dockerfile
        - image: hashicorpdev/consul-helm-test:0.3.0

    steps:
        - checkout

        - run:
            name: terraform init & apply
            command: |
                terraform init test/terraform
                echo $GOOGLE_APP_CREDS | base64 -d > vault-helm-test.json
                gcloud auth activate-service-account --key-file=vault-helm-test.json

                terraform apply -var project=${CLOUDSDK_CORE_PROJECT} -var init_cli=true -auto-approve test/terraform

        - run:
            name: Run acceptance tests
            command: bats ./test/acceptance -t

        - run:
            name: terraform destroy
            command: |
                terraform destroy -auto-approve
            when: always

  update-helm-charts-index:
    docker:
      - image: circleci/golang:latest
    steps:
      - run:
          name: update helm-charts index
          command: |
            curl --show-error --silent --fail --user "${CIRCLE_TOKEN}:" \
                -X POST \
                -H 'Content-Type: application/json' \
                -H 'Accept: application/json' \
                -d "{\"branch\": \"master\",\"parameters\":{\"SOURCE_REPO\": \"${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}\",\"SOURCE_TAG\": \"${CIRCLE_TAG}\"}}" \
                "${CIRCLE_ENDPOINT}/${CIRCLE_PROJECT}/pipeline"

workflows:
  version: 2
  build_and_test:
    jobs:
      - bats-unit-test
      - acceptance:
            requires:
                - bats-unit-test
            filters:
                branches:
                    only: add-acceptance-tests-ci
  update-helm-charts-index:
    jobs:
      - update-helm-charts-index:
          context: helm-charts-trigger
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
